### ISSUE TITLE
rn在android中运行git示例时出现null is not an object(evaluation this.scrollView.scrollTo)

### ISSUE THREAD

**Issue by shaojiaqi08** [tmxiong/better-banner#1]
下载此插件并运行在android中直接报错
`{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-better-banner": "^1.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

运行代码为：
`import React, {Component} from 'react';
import {StyleSheet, View, Text, Image} from 'react-native';

import BetterBanner from 'react-native-better-banner';

export default class Rnswiper extends Component {
  render() {
    return (
      <View style={styles.container}>
        <BetterBanner
          bannerImages={[
            {
              uri:
                'http://attachments.gfan.net.cn/forum/attachments2/201402/05/211339r5eizavo2g5efuar.jpg.thumb.jpg',
            },
            {
              uri:
                'http://attachments.gfan.net.cn/forum/attachments2/201402/05/211342pkd8axiibj5axizi.jpg.thumb.jpg',
            },
            {
              uri:
                'http://attachments.gfan.net.cn/forum/attachments2/201402/05/2113441e4dw5zvv49jkdow.jpg.thumb.jpg',
            },
            {
              uri:
                'http://attachments.gfan.net.cn/forum/attachments2/201402/05/2113472s3y3y1w62n2io6y.jpg.thumb.jpg',
            },
          ]}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
`

**Comment by shaojiaqi08** [comment]
而且奇怪的是，在android中进行多次reload有小概率正常运行，但是只要重新刷新就会报错

**Comment by zhoushihao-creat** [comment]
在Android运行时，会出现TypeError:null is not an object(evaluating'this.scrollView.scrollTo')，一旦保存代码刷新会出现，但是reload的时候会有概率不报错而正常运行

**Comment by tmxiong** [comment]
版本`1.1.3`中已修复该问题，如已安装旧版，请执行`npm install --save react-native-better-banner@latest`获取最新版
